#!/bin/bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

if [ ! -f $HOME/.gitconfig ]; then
  cp $DOTFILES/.gitconfig $HOME/.gitconfig
fi
ln -isv $DOTFILES/.zshrc $HOME/.zshrc
ln -isv $DOTFILES/.hgrc $HOME/.hgrc
ln -isv $DOTFILES/.sqliterc $HOME/.sqliterc
# dirs use if because if you install twice, ln will put a folder in a folder
if [ ! -s $HOME/.config/nvim ]; then
  mkdir -p $HOME/.config
  ln -isv "$DOTFILES/nvim" "$HOME/.config/nvim"
fi
if [ ! -s $HOME/.config/tmux ]; then
  mkdir -p $HOME/.config
  ln -isv "$DOTFILES/tmux" "$HOME/.config/tmux"
fi
if [ ! -s $HOME/.zshrc.d ]; then
  ln -isv $DOTFILES/.zshrc.d $HOME/.zshrc.d
fi
if [ ! -s $HOME/bin ]; then
  ln -isv $DOTFILES/bin $HOME/bin
fi
if [ ! -s $HOME/.config/git/ignore ]; then
  mkdir -p $HOME/.config/git
  ln -isv $DOTFILES/gitignore $HOME/.config/git/ignore
fi
