#!/bin/bash

HERE=$(dirname ${BASH_SOURCE[0]})

cp -i $HERE/.gitconfig ~/.gitconfig
ln -isv $HERE/.gvimrc ~/.gvimrc
ln -isv $HERE/.hgrc ~/.hgrc
if [ ! -s ~/.vimrc ]
then
	# this is in an if because if you install twice it will put .vim inside of .vim
	ln -isv $HERE/.vim ~/.vim
fi
ln -isv $HERE/.vimrc ~/.vimrc

