#!/bin/bash

set -e

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

cp -i $DOTFILES/.gitconfig ~/.gitconfig
ln -isv $DOTFILES/.gvimrc ~/.gvimrc
ln -isv $DOTFILES/.hgrc ~/.hgrc
# this is in an if because if you install twice it will put .vim inside of .vim
if [ ! -s ~/.vim ]; then
	ln -isv $DOTFILES/.vim ~/.vim
fi
if [ ! -s ~/.vimrc ]; then
	ln -isv $DOTFILES/.vimrc ~/.vimrc
fi

