#!/bin/bash

set -e

infile=$1
outfile=$2

if [[ -z "$infile" ]]; then
	echo "usage: $0 filename.mov"
	exit -1
fi

if [[ -z "$outfile" ]]; then
	outfile=$(echo -n "$infile" | sed -e 's/MOV$/mp4/I')
	if [[ -f "$outfile" ]]; then
		echo "$outfile already exists"
		exit -1
	fi
fi

ffmpeg -i "$infile" -vf scale=720:-1,fps=30 -c:v libx264 -crf 23 -preset slower "$outfile"

