#!/bin/bash
if [ ! -f "$1" ]; then
	echo "Usage: gifff filename.mov"
	exit 1
fi
echo "Making gif"
set -i

# better options here
# http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html
ffmpeg -v warning -i "$1" -vf fps=10,scale=400:-1 "$1.gif"
